language: python

python:
 - "3.6"

install: pip install -e .

script:
  - pip install -r requirements.txt

deploy:
  provider: pypi
  user: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDUxN2U2Mjg1LTQwNTYtNGFkMy04ZTA2LWNkMjllMDYwNjgxZgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgOMSVGCUSp_lfobjG-HchTk9-9R_U-QAZ9tm0pT99W38"
  on:
    branch: master
